# https://pre-commit.com/hooks.html
# pre-commit run -a
exclude: ^archive/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-ast
  - id: check-executables-have-shebangs
  - id: double-quote-string-fixer
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: check-shebang-scripts-are-executable
  - id: detect-private-key
  - id: destroyed-symlinks
  - id: check-symlinks
  - id: check-case-conflict
  - id: check-json
  - id: pretty-format-json
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.0
  hooks:
  - id: autopep8
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
  - id: codespell
    args:
    - --write-changes
autoupdate_schedule: quarterly
