#!/usr/bin/python3
import argparse
import click
import collections
import chardet


def detect_file_encoding(filename):
    with open(filename, 'rb') as file:
        raw_data = file.read()
        return chardet.detect(raw_data)['encoding']


parser = argparse.ArgumentParser()
parser.add_argument('filepath')
parser.add_argument('-l', '--limit', action='store_true')
args = parser.parse_args()

counts = collections.Counter()
encoding = detect_file_encoding(args.filepath)
click.secho(f'Reading {args.filepath} with encoding {encoding}', fg='bright_white')

for line in open(args.filepath, encoding=encoding).readlines():
    for c in line:
        counts[c] += 1

valid = True
for c, n in counts.most_common():
    code = ord(c)
    if code > 255:
        valid = False
        color = 'red'
    elif args.limit:
        continue
    else:
        color = 'blue'

    click.secho(f'{n:5d} ', nl=False, fg=color)
    click.secho(f'{code:5d} ', nl=False, fg=f'bright_{color}')
    click.secho(f'{repr(c)}', fg=color)

if valid:
    click.secho('All characters ASCII', fg='bright_green')
