#!/usr/bin/python3

import argparse
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument('filenames', nargs='+')
args = parser.parse_args()

for filename in args.filenames:
    cmd = ['convert', filename, '-flatten']
    # -fuzz 1% -trim +repage trimmed.jpg
    cmd += ['-trim', '+repage', filename]
    subprocess.call(cmd)
