#!/usr/bin/python

import subprocess
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('repo')
parser.add_argument('distro')

args = parser.parse_args()

subprocess.call(['bloom-release', args.repo, '--track', args.distro, '--rosdistro', args.distro])
