#!/usr/bin/env python3
import argparse
import pathlib
import re
import subprocess
import tempfile
import yaml

POINTS_PER_INCH = 72
PIXELS_PER_INCH = 300

PDF_PATTERN = re.compile(r'\.pdf(\[\d+\])?')


def pdf_convert(input_filename, ratio):
    temp_pdf = tempfile.NamedTemporaryFile(suffix='.pdf')
    subprocess.call(['convert', '-density', '300', str(input_filename),
                     '-gravity', 'center', '-extent', ratio,
                     temp_pdf.name])

    return [temp_pdf]

def xcf_convert(input_filename, ratio):
    temp_pdf = tempfile.NamedTemporaryFile(suffix='.pdf')
    with tempfile.NamedTemporaryFile(suffix='.png') as temp_png:
        subprocess.call(['xcf2png', str(input_filename), '-o', temp_png.name])  # xcftools
        subprocess.call(['convert', temp_png.name, '-page', ratio, temp_pdf.name])

    return temp_pdf


def png_convert(input_filename, ratio):
    temp_pdf = tempfile.NamedTemporaryFile(suffix='.pdf')
    subprocess.call(['convert', str(input_filename), '-gravity', 'center', '-extent', ratio, temp_pdf.name])
    return temp_pdf


def tex_convert(input_filename):
    pdf_filename = pathlib.Path(input_filename.stem + '.pdf')
    subprocess.call(['xelatex', str(input_filename)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    for suffix in ['.aux', '.log']:
        junk = pdf_filename.with_suffix(suffix)
        if junk.exists():
            junk.unlink()

    return pdf_filename


parser = argparse.ArgumentParser()
parser.add_argument('folder', type=pathlib.Path)
parser.add_argument('output', nargs='?', type=pathlib.Path)
parser.add_argument('-w', '--width', default=5.5, type=float)
parser.add_argument('--height', default=8.5, type=float)
args = parser.parse_args()

layout = yaml.load(open(args.folder / 'layout.yaml'))
files = []
to_delete = []

points_ratio = f'{int(args.width * POINTS_PER_INCH)}x{int(args.height * POINTS_PER_INCH)}'
pixels_ratio = f'{int(args.width * PIXELS_PER_INCH)}x{int(args.height * PIXELS_PER_INCH)}'

for section in layout:
    if isinstance(section, str):
        filename = section
    else:
        filename = section['file']

    fp = args.folder / filename
    print(fp)
    if fp.suffix == '.xcf':
        files.append(xcf_convert(fp, points_ratio))
    elif PDF_PATTERN.match(fp.suffix):
        files += pdf_convert(fp, pixels_ratio)
    elif fp.suffix == '.tex':
        pdf = tex_convert(fp)
        to_delete.append(pdf)
        files.append(pdf)
    elif fp.suffix == '.png':
        files.append(png_convert(fp, pixels_ratio))
    else:
        print(f'unknown suffix {fp.suffix}')

if args.output is None:
    args.output = args.folder / 'output.pdf'

subprocess.call(['pdftk'] + [x.name for x in files] + ['cat', 'output', str(args.output)])

for fn in to_delete:
    fn.unlink()
