#!/usr/bin/python3
from googly import GMailAPI
import argparse
import pathlib
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument('title')
parser.add_argument('-e', '--error-only', action='store_true')
parsed_args, cmd = parser.parse_known_args()


p = subprocess.run(cmd, capture_output=True)
out = p.stdout.decode()
err = p.stderr.decode()

if not out and not err:
    exit(0)
elif parsed_args.error_only:
    if not err:
        exit(0)
    out = ''

# Check if out or err
head = ' '.join(cmd)
body = f"""
<h3 style="font-family: monospace">{head}</h3>
<pre>
{out}
</pre>
<pre style="color: red">
{err}
</pre>
"""

cred_path = pathlib.Path('/home/dlu/Projects/probablyscripts/credentials.json')
gmail = GMailAPI(
    project_credentials_path=cred_path
)

gmail.send_email(subject=parsed_args.title, body=body,
                 send_from='Monolith <davidvlu@gmail.com>',
                 send_to=['davidvlu@gmail.com'],
                 html=True,
                 )
