#!/usr/bin/python3

import argparse
import click
import subprocess
import json

parser = argparse.ArgumentParser()
parser.add_argument('-l', '--latest', action='store_true')
parser.add_argument('name', nargs='?')
args = parser.parse_args()

ps_cmd = ['docker', 'ps', '--format', 'json']
if args.latest:
    ps_cmd.append('-l')

containers_bs = subprocess.check_output(ps_cmd)
containers = []
for line in containers_bs.decode().split('\n'):
    if not line:
        continue
    container = json.loads(line)
    container['image'], container['tag'] = container['Image'].split(':')
    if 'buildkit' in container['image']:
        continue
    containers.append(container)

if args.name:
    containers = [container for container in containers if container['image'] == args.name]

if len(containers) == 1:
    container = containers[0]
else:
    names = [container['image'] for container in containers]
    raise RuntimeError('too many values: ' + ' '.join(names))

click.secho('Attaching to ', fg='blue', nl=False)
click.secho(container['Image'], fg='bright_blue')

subprocess.call(['docker', 'exec', '-it', container['ID'], 'bash'])
