#!/usr/bin/python3

import subprocess
import argparse
import pathlib

parser = argparse.ArgumentParser()
parser.add_argument('filenames', metavar='filename', nargs='+', type=pathlib.Path)
args = parser.parse_args()

THIS_FOLDER = pathlib.Path(__file__).parent
config = (THIS_FOLDER / '.clang-format').resolve()

local_config = pathlib.Path('.clang-format')
unlink = False
if not local_config.exists():
    local_config.symlink_to(config)
    unlink = True


print(subprocess.call(['clang-format', '-i', '--style=file'] + [str(f) for f in args.filenames]))


if unlink:
    local_config.unlink()
