#!/usr/bin/env python3
import argparse
import os

import click

TEXT = {
    ' \n': '\n',
    '\r\n': '\n'
}

parser = argparse.ArgumentParser()
parser.add_argument('-v', '--verbose', action='store_true')
args = parser.parse_args()

for path, folders, files in os.walk('.'):
    if '.git' in path:
        continue
    for file in files:
        full_path = os.path.join(path, file)
        s = ''
        try:
            with open(full_path, 'r') as f:
                s = f.read()
        except UnicodeDecodeError:
            if args.verbose:
                click.secho(f'Skipping {full_path}...', fg='yellow')
            continue

        changed = False
        keep_iterating = True
        while keep_iterating:
            keep_iterating = False
            for needle, replacement in TEXT.items():
                if needle in s:
                    s = s.replace(needle, replacement)
                    keep_iterating = True
                    changed = True

        if changed:
            click.secho(f'Updating {full_path}...', fg='green')
            with open(full_path, 'w') as f:
                f.write(s)
        elif args.verbose:
            click.secho(f'No changes needed for {full_path}...', fg='blue')
