#!/usr/bin/python

import subprocess
import re
import os
import collections

pwd = os.environ['PWD']
PATTERN = re.compile('\[[^\]]*\] ([^:]+):(\d+):(.*) \[(.*)\] \[(.*)\]')

p = subprocess.Popen(['catkin', 'build', '-v', '-i', '--this', '--no-deps', '--catkin-make-args', 'roslint'],
                     stdout=subprocess.PIPE, stderr=subprocess.PIPE)
output, err = p.communicate()

tally = collections.defaultdict(int)

last_filename = ''
c = 0
for line in err.split('\n'):
    if 'Done processing' in line:
        if c > 0:
            print
        continue
    line = line.strip()

    m = PATTERN.match(line)
    if m:
        filename, line_no, msg, cat, n = m.groups()
        filename = filename.replace(pwd, '')
        if last_filename != filename:
            print filename
            c = 0
            last_filename = filename
        line_no = int(line_no)
        n = int(n)
        msg = msg.strip()
        print 'Line %4d %-25s(%d) %s' % (line_no, cat, n, msg)
        c += 1
        tally[cat] += 1

for cat, count in sorted(tally.items(), key=lambda g: g[1]):
    print cat, count
