#!/usr/bin/python

import subprocess
import re

PATTERN = re.compile('\\x1b\[36mRunning tests...\r\n\\x1b\[0m[^\n]+\n(.*Total Test time \(real\) = [^\n]+\n)',
                     re.DOTALL
                     )

ret = subprocess.call(['catkin', 'build', '--this', '--no-deps', '--catkin-make-args', 'run_tests'])
if ret != 0:
    exit(ret)

p = subprocess.Popen(['catkin', 'test', '--this', '--no-deps'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
output, err = p.communicate()
#output = subprocess.check_output()
m = PATTERN.search(output)
if not m:
    print repr(output)
    exit(0)
print m.group(1)
exit(p.returncode)
